services:
  - type: web
    name: hmd-relay-server
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: FCM_PROJECT_ID
        sync: false
      - key: FCM_SERVICE_ACCOUNT_JSON
        sync: false
